/**
 * stdlib_round_trip.test.ts — golden equivalence at the stdlib loader.
 *
 * For every `stdlib/<name>.json` there is a sibling `stdlib/<name>.trop`
 * generated by `convert_stdlib.ts`. This test asserts that loading a
 * stdlib through either path produces structurally-identical results in
 * the session registries:
 *
 *   - genericTemplates entries (legacy ProgramNode templates) deep-equal
 *   - typeRegistry entries' ProgramDef deep-equal (after SignalExpr →
 *     ExprNode normalization and recursive nestedCalls normalization)
 *   - typeAliasRegistry, sumTypeRegistry, structTypeRegistry deep-equal
 *
 * Path A (legacy):    JSON  → normalizeProgramFile → loadStdlibFromMap
 * Path B (parsed):    .trop → extractMarkdown → parseProgram → lowerProgram
 *                          → wrap as v2 file → loadStdlibFromMap
 *
 * Path B feeds the lowered ProgramNode back through normalizeProgramFile
 * (the same gate the legacy path uses) by wrapping it as a v2 file. This
 * keeps the loader codepath identical between the two paths; the only
 * difference is the IR's provenance.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, test, expect } from 'bun:test'
import { loadStdlibFromMap } from '../stdlib_loader.js'
import { extractMarkdown } from './markdown.js'
import { parseProgram } from './declarations.js'
import { lowerProgram } from './lower.js'
import type { ProgramType, ProgramDef, NestedCall } from '../program_types.js'
import type { SessionState } from '../session.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const stdlibDir = join(__dirname, '../../stdlib')

// ─────────────────────────────────────────────────────────────
// Session shaping
// ─────────────────────────────────────────────────────────────

type StdlibSession = Pick<
  SessionState,
  | 'typeRegistry'
  | 'instanceRegistry'
  | 'paramRegistry'
  | 'triggerRegistry'
  | 'specializationCache'
  | 'genericTemplates'
  | 'typeAliasRegistry'
  | 'sumTypeRegistry'
  | 'structTypeRegistry'
>

function freshSession(): StdlibSession {
  return {
    typeRegistry: new Map(),
    instanceRegistry: new Map(),
    paramRegistry: new Map(),
    triggerRegistry: new Map(),
    specializationCache: new Map(),
    genericTemplates: new Map(),
    typeAliasRegistry: new Map(),
    sumTypeRegistry: new Map(),
    structTypeRegistry: new Map(),
  }
}

// ─────────────────────────────────────────────────────────────
// Path A — load from JSON
// ─────────────────────────────────────────────────────────────

function loadFromJson(): StdlibSession {
  const session = freshSession()
  const files = readdirSync(stdlibDir).filter(f => f.endsWith('.json')).sort()
  const rawByName = new Map<string, unknown>()
  for (const file of files) {
    const raw = JSON.parse(readFileSync(join(stdlibDir, file), 'utf-8')) as { name?: string }
    if (typeof raw.name !== 'string') throw new Error(`${file}: missing 'name' field`)
    rawByName.set(raw.name, raw)
  }
  loadStdlibFromMap(session, rawByName)
  return session
}

// ─────────────────────────────────────────────────────────────
// Path B — load from .trop
// ─────────────────────────────────────────────────────────────

function loadFromTrop(): StdlibSession {
  const session = freshSession()
  const files = readdirSync(stdlibDir).filter(f => f.endsWith('.trop')).sort()
  const rawByName = new Map<string, unknown>()
  for (const file of files) {
    const text = readFileSync(join(stdlibDir, file), 'utf-8')
    const ext = extractMarkdown(text)
    if (ext.blocks.length !== 1) {
      throw new Error(`${file}: expected exactly 1 tropical block, got ${ext.blocks.length}`)
    }
    const parsed = parseProgram(ext.blocks[0].source)
    const lowered = lowerProgram(parsed)
    // Re-package as a v2 file so loadStdlibFromMap can normalize it
    // through the same path as the JSON loader. Strip `op:'program'`
    // (file-shape carries fields directly) and inject the schema tag.
    const { op: _op, ...fields } = lowered as unknown as Record<string, unknown>
    void _op
    const file2 = { schema: 'tropical_program_2', ...fields }
    if (typeof file2.name !== 'string') throw new Error(`${file}: lowered program missing name`)
    rawByName.set(file2.name as string, file2)
  }
  loadStdlibFromMap(session, rawByName)
  return session
}

// ─────────────────────────────────────────────────────────────
// ProgramDef normalization
// ─────────────────────────────────────────────────────────────

/** Convert a ProgramDef into a plain JSON-serializable structure suitable
 *  for `expect(...).toEqual(...)`. SignalExpr instances are reduced to
 *  their `_node` payload; nestedCalls' `programDef` references are
 *  normalized recursively (these reference the *same* ProgramDef shared
 *  by the registry, but normalizing them in place removes any structural
 *  differences caused by the loader's internal state). */
function normalizeDef(def: ProgramDef, seen: WeakMap<ProgramDef, unknown>): unknown {
  const cached = seen.get(def)
  if (cached !== undefined) return cached
  const out: Record<string, unknown> = {}
  seen.set(def, out)

  out.typeName = def.typeName
  out.inputNames = def.inputNames
  out.outputNames = def.outputNames
  out.registerNames = def.registerNames
  out.registerInitValues = def.registerInitValues
  out.sampleRate = def.sampleRate
  out.rawInputDefaults = def.rawInputDefaults
  out.inputDefaults = def.inputDefaults.map(d => d === null ? null : { node: d._node, shape: d.shape })
  out.delayInitValues = def.delayInitValues
  out.outputExprNodes = def.outputExprNodes
  out.registerExprNodes = def.registerExprNodes
  out.delayUpdateNodes = def.delayUpdateNodes
  out.breaksCycles = def.breaksCycles
  out.inputBounds = def.inputBounds
  out.outputBounds = def.outputBounds
  // PortType objects are class instances but their fields are plain JSON.
  // toEqual compares by structure for plain-ish objects; safe here.
  out.inputPortTypes = def.inputPortTypes
  out.outputPortTypes = def.outputPortTypes
  out.registerPortTypes = def.registerPortTypes
  out.nestedCalls = def.nestedCalls.map((nc: NestedCall) => ({
    programDef: normalizeDef(nc.programDef, seen),
    callArgNodes: nc.callArgNodes,
  }))
  return out
}

function normalizeType(type: ProgramType): unknown {
  return normalizeDef(type._def, new WeakMap())
}

/** Strip the legacy `body.value: null` placeholder from a ProgramNode tree
 *  in place. Pre-A4 stdlib files keep this carry-over from the v1 schema;
 *  the parser/lower chain does not emit it. The placeholder is purely
 *  vestigial — the loader ignores it — so normalizing it out for the
 *  comparison is sound. */
function stripBodyValueNulls(node: unknown): void {
  if (Array.isArray(node)) {
    for (const x of node) stripBodyValueNulls(x)
    return
  }
  if (node === null || typeof node !== 'object') return
  const obj = node as Record<string, unknown>
  if (obj.op === 'block' && obj.value === null) delete obj.value
  for (const v of Object.values(obj)) stripBodyValueNulls(v)
}

// ─────────────────────────────────────────────────────────────
// The test
// ─────────────────────────────────────────────────────────────

describe('stdlib round-trip — JSON ↔ .trop equivalence at the loader', () => {
  const sessionA = loadFromJson()
  const sessionB = loadFromTrop()

  test('same set of generic templates', () => {
    const namesA = [...sessionA.genericTemplates.keys()].sort()
    const namesB = [...sessionB.genericTemplates.keys()].sort()
    expect(namesB).toEqual(namesA)
  })

  test('same set of registered types', () => {
    const namesA = [...sessionA.typeRegistry.keys()].sort()
    const namesB = [...sessionB.typeRegistry.keys()].sort()
    expect(namesB).toEqual(namesA)
  })

  test('generic templates deep-equal', () => {
    for (const [name, tmplA] of sessionA.genericTemplates) {
      const tmplB = sessionB.genericTemplates.get(name)
      // Normalize away legacy `body.value: null` placeholders that the
      // pre-A4 JSON files carry but the parser does not emit. Both sides
      // are mutated in place before comparison.
      stripBodyValueNulls(tmplA)
      if (tmplB !== undefined) stripBodyValueNulls(tmplB)
      expect(tmplB).toEqual(tmplA)
    }
  })

  test('non-generic ProgramDefs deep-equal', () => {
    for (const [name, typeA] of sessionA.typeRegistry) {
      const typeB = sessionB.typeRegistry.get(name)
      if (typeB === undefined) throw new Error(`type '${name}' missing from .trop session`)
      expect(normalizeType(typeB)).toEqual(normalizeType(typeA))
    }
  })

  test('typeAliasRegistry deep-equal', () => {
    expect(sessionB.typeAliasRegistry).toEqual(sessionA.typeAliasRegistry)
  })

  test('sumTypeRegistry deep-equal', () => {
    expect(sessionB.sumTypeRegistry).toEqual(sessionA.sumTypeRegistry)
  })

  test('structTypeRegistry deep-equal', () => {
    expect(sessionB.structTypeRegistry).toEqual(sessionA.structTypeRegistry)
  })
})
