"""karplus — the weekend proof that Karplus-Strong is a modal bank.

The delay line was 1983's cheapest way to evaluate a plucked string on a
6502. Underneath the recurrence is an LTI system, and Jaffe & Smith (1984)
wrote down its exact structure: the loop

    y[n] = x[n] + rho * (1/2) * (y[n-N] + y[n-N-1])

is a rational filter Y(z) = X(z) / A(z) with A(z) = 1 - (rho/2)(z^-N + z^-{N+1}).
Its poles are ~N complex pairs near the unit circle, harmonically spaced at
multiples of fs/(N+1/2), each with its own decay set by |G| = cos(w/2):

    partial k  ~  A_k * e^{-t/tau_k} * cos(w_k t + phi_k),
    w_k = 2*pi*k/(N+1/2),   |pole|_k = (rho*cos(w_k/2))^{1/(N+1/2)}.

Highs die faster, lows sustain -- that frequency-dependent decay IS the
plucked-string sound. So a KS string is a modal bank whose pole table is
GENERATED by the loop equation, and the noise burst -- the part that seems
most essentially stateful -- just determines the residues: project the
excitation onto the modes and you get the amplitudes and phases. Make the
burst hash(seed, k) and every pluck becomes a coordinate, not an event:
deterministic, bit-exact, tau-addressable, and scrubbable backward -- you
can reverse a guitar note with zero latency, which no delay-line KS can do,
because their pluck is entropy that already left the building and ours is a
seed that never does.

This is the gong.py method applied to the one algorithm everyone believes
requires state: numpy KS RECURRENCE as the oracle, closed-form MODAL render
as the candidate, SNR gate as the referee (the two-realization differential).
Everything here is closed-form in a time coordinate -- engine-expressible as
a `bankSum` over a data pole table -- so the recipe can be tuned by ear
before any Lean work.

Honest boundary: what stays impossible is feedback entangled with the
UNKNOWN -- bowing a live input into the loop. A cycle among KNOWNS is not
state; it is a linear system, and linear systems have closed-form solutions.
That is the whole trick. Sustained nonlinear excitation (bowing) sits at the
Volterra edge and is the genuinely ceded island.
"""
import numpy as np
import wave
import os
from scipy.signal import lfilter

SR = 44100
OUT = os.path.dirname(os.path.abspath(__file__))
MASK64 = (1 << 64) - 1


# ================================================================ the loop, diagonalized

def ks_denominator(N, rho):
    """A(z) as a descending-power polynomial P(z) = z^{N+1} - (rho/2)z - rho/2.
    (A(z) = 1 - (rho/2)(z^-N + z^-{N+1}), multiplied through by z^{N+1}.)"""
    P = np.zeros(N + 2)
    P[0] = 1.0                 # z^{N+1}
    P[-2] = -rho / 2.0         # z^1
    P[-1] = -rho / 2.0         # z^0
    return P


def ks_poles(N, rho):
    """The pole table: ~N complex pairs near the unit circle. These are the
    modes -- roots of the loop denominator, found once, then DATA."""
    return np.roots(ks_denominator(N, rho))


def ks_residues(burst, N, rho):
    """Project the burst onto the modes. Y(z) = Xnum(z)/P(z) with both degree
    N+1, so residue A_i = num(p_i)/P'(p_i) and one direct (click) term. The
    burst is the excitation; the residues are its coordinates in mode space --
    a linear image of the burst, so a hashed burst gives hashed residues."""
    P = ks_denominator(N, rho)
    p = np.roots(P)
    num = np.concatenate([burst, [0.0, 0.0]])   # burst[m] -> z^{N+1-m}
    A = np.polyval(num, p) / np.polyval(np.polyder(P), p)
    return p, A, burst[0]                        # poles, residues, y[0] click


# ---- realization 1: the ORACLE (stateful delay-line recurrence) ----

def ks_recurrence(burst, N, rho, nsamp):
    """1983's realization: run the actual feedback loop, one sample at a time."""
    a = np.concatenate([[1.0], np.zeros(N - 1), [-rho / 2, -rho / 2]])
    x = np.zeros(nsamp)
    x[:len(burst)] = burst
    return lfilter([1.0], a, x)


# ---- realization 2: the CANDIDATE (closed-form modal sum) ----

def ks_modal(burst, N, rho, nsamp):
    """1984's realization: diagonalize and render the solution. No loop, no
    state -- y[n] = Σ_i A_i p_i^{n-1}, a pure function of the sample index n."""
    p, A, click = ks_residues(burst, N, rho)
    n = np.arange(nsamp)
    y = (A[:, None] * np.power.outer(p, np.maximum(n - 1, 0))).sum(0)
    y[0] = click
    return y.real


# ================================================================ the burst is a coordinate

def hash_noise(pos):
    """The stdlib HashNoise finalizer: splitmix over the coordinate. A pluck
    is not entropy that left the building -- it is a read at `pos`, forever."""
    n = int(pos) & MASK64
    h = n ^ (n >> 31)
    h = (h * 2685821657736338717) & MASK64
    h = h ^ (h >> 27)
    h = (h * 2685821657736338717) & MASK64
    h = h ^ (h >> 33)
    return (h & 65535) * 2.0 / 65535.0 - 1.0


def hash_burst(seed, N, stride=1_000_003):
    """Pluck `seed` = a disjoint window of the ONE HashNoise sequence. Every
    pluck is a coordinate: bit-exact, reproducible, and (unlike a PRNG walk)
    random-access -- so its residues are addressable and its render reverses."""
    base = (seed * stride) & MASK64
    return np.array([hash_noise(base + m) for m in range(N)])


# ================================================================ closed-form edits (poles/residues are DATA)

def pick_comb(burst, N, d):
    """Pick at fractional position d combs the excitation: x -> x - x shifted
    by round(d*N). Partial k is scaled by |sin(pi k d)| -- a node at the pick
    point is silent. Closed form, applied to DATA before projection."""
    s = int(round(d * N)) % N
    return burst - np.roll(burst, s)


def stiffen_poles(p, B, N):
    """Stiffness / inharmonicity is a STRETCH of the pole table: partial k
    rides up to f_k = k*f0*sqrt(1 + B k^2). Poles are data now, so dispersion
    is an edit to the angle column -- no new algorithm, no waveguide allpass
    chain. Mode index k = angle / w_1, so the stretch keys off the loop table
    itself (piano B ~ 4e-4; larger B -> gong/tine)."""
    mag, ang = np.abs(p), np.angle(p)
    w1 = 2 * np.pi / (N + 0.5)                              # fundamental spacing
    k = ang / w1                                            # signed mode index
    ang2 = np.clip(ang * np.sqrt(1.0 + B * k * k),
                   -np.pi + 1e-9, np.pi - 1e-9)
    return mag * np.exp(1j * ang2)


def render_from_table(p, A, click, taus):
    """Eval the mode bank on ANY time grid `taus` (sample units). Warped,
    reversed, jumped -- the modes are f(n), so this is the forgetful map
    Modal -> Signal. Continuous pole lam = ln(p); amp folds the n-1 shift."""
    lam = np.log(p)                       # per-sample log-pole (complex)
    amp = A / p                           # absorb the p^{n-1} vs p^n shift
    y = np.zeros(len(taus), dtype=complex)
    on = taus > 0
    tt = np.where(on, taus, 0.0)
    for lm, am in zip(lam, amp):
        y += am * np.exp(lm * tt)
    y = np.where(on, y.real, 0.0)
    y[np.abs(taus) < 0.5] += click        # the one-sample click at the onset
    return y


# ================================================================ output

def write_wav(path, y, gain=0.9):
    assert np.all(np.isfinite(y)), "non-finite samples"
    y = np.asarray(y, float)
    y = y / (np.max(np.abs(y)) + 1e-12) * gain
    f = int(0.005 * SR)
    env = np.ones(len(y))
    env[:f] = np.linspace(0, 1, f)
    env[-f:] = np.linspace(1, 0, f)
    y = y * env
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes((y * 32767).astype(np.int16).tobytes())
    print(f"  wrote {os.path.basename(path):28s} ({len(y)/SR:5.2f}s, "
          f"rms {np.sqrt(np.mean(y**2)):.3f})")


def place(canvas, y, t0):
    i0 = int(t0 * SR)
    n = min(len(y), len(canvas) - i0)
    if n > 0:
        canvas[i0:i0 + n] += y[:n]


# ================================================================ proof + renders

def prove(N=100, rho=0.996, seed=17, dur=3.0):
    """The two-realization differential: recurrence oracle vs modal candidate,
    plus the Jaffe-Smith closed-form check that the pole table IS the loop."""
    nsamp = int(dur * SR)
    burst = hash_burst(seed, N)

    y_oracle = ks_recurrence(burst, N, rho, nsamp)
    y_modal = ks_modal(burst, N, rho, nsamp)

    err = y_modal - y_oracle
    snr = 10 * np.log10(np.sum(y_oracle**2) / np.sum(err**2))
    print(f"— two-realization differential (N={N}, rho={rho}, seed={seed}) —")
    print(f"  recurrence (stateful)  vs  modal (closed-form)")
    print(f"  SNR = {snr:6.1f} dB   max|err| = {np.max(np.abs(err)):.2e}   "
          f"[{'PASS' if snr > 120 else 'FAIL'} @ 120 dB]")

    # Jaffe-Smith: measured poles vs the closed form generated by the loop
    p = ks_poles(N, rho)
    ang = np.angle(p)
    print("  partial   f_meas(Hz)  f_pred=k*fs/(N+.5)   tau_k(s)   (highs die faster)")
    for k in range(1, 6):
        wpred = 2 * np.pi * k / (N + 0.5)
        i = np.argmin(np.abs(ang - wpred))
        fmeas = ang[i] * SR / (2 * np.pi)
        tau = -1.0 / (SR * np.log(np.abs(p[i])))
        print(f"    k={k}    {fmeas:9.2f}   {k*SR/(N+0.5):12.2f}      {tau:7.3f}")

    # seed-addressability: same seed -> bit-exact; different seed -> different
    b2 = hash_burst(seed, N)
    print(f"  seed {seed} is a coordinate: replay bit-exact = "
          f"{np.array_equal(burst, b2)};  "
          f"seed {seed} != seed {seed+1}: {not np.array_equal(burst, hash_burst(seed+1, N))}")
    return snr


def render_reversible(N=120, rho=0.997, seed=17, dur=2.0):
    """Reverse a guitar note with zero latency. Render the SAME mode table on
    a forward-then-reverse clock; because the modes are f(n) the decay scrubs
    back into a swell, bit-exact -- a palindrome no delay-line KS can produce."""
    burst = hash_burst(seed, N)
    p, A, click = ks_residues(burst, N, rho)
    half = int(dur * SR)
    fwd = np.arange(half, dtype=float)
    clock = np.concatenate([fwd, fwd[::-1]])        # symmetric triangle in n
    y = render_from_table(p, A, click, clock)
    pal = np.allclose(y, y[::-1], atol=1e-9)
    print(f"— reversible pluck — palindrome bit-exact: {pal}")
    write_wav(f"{OUT}/karplus_reverse.wav", y)


def render_pick_sweep(N=110, rho=0.996):
    """Pick position d combs the residues by sin(pi k d): a closed-form edit
    to the excitation, four plucks from bridge (d~0.1) to middle (d=0.5)."""
    print("— pick-position sweep (bright -> hollow) —")
    canvas = np.zeros(int(8 * SR))
    for i, d in enumerate([0.10, 0.22, 0.35, 0.50]):
        burst = pick_comb(hash_burst(3 + i, N), N, d)
        y = ks_modal(burst, N, rho, int(2 * SR))
        place(canvas, y, 0.4 + 1.8 * i)
    write_wav(f"{OUT}/karplus_pick_sweep.wav", canvas)


def render_stiffness_sweep(N=90, rho=0.995):
    """Inharmonicity as a pole-table stretch: piano-like partials from a
    stiffness knob B. Poles are data; dispersion is an edit, not an algorithm."""
    print("— stiffness sweep (string -> tine) —")
    canvas = np.zeros(int(8 * SR))
    burst = hash_burst(42, N)
    p0, A, click = ks_residues(burst, N, rho)
    for i, B in enumerate([0.0, 0.0004, 0.0015, 0.006]):
        p = stiffen_poles(p0, B, N)
        taus = np.arange(int(2 * SR), dtype=float)
        y = render_from_table(p, A, click, taus)
        place(canvas, y, 0.4 + 1.8 * i)
    write_wav(f"{OUT}/karplus_stiffness_sweep.wav", canvas)


def render_phrase(rho=0.997):
    """A little phrase, each note addressed by (pitch, seed). Pitch = delay
    length N ~ fs/f. The whole melody is a table of coordinates."""
    print("— seed-addressed phrase —")
    canvas = np.zeros(int(9 * SR))
    #        t    freq   seed
    notes = [(0.2, 196.0, 11), (0.9, 246.9, 12), (1.6, 293.7, 13),
             (2.3, 392.0, 14), (3.0, 293.7, 15), (3.7, 246.9, 16),
             (4.4, 329.6, 17), (5.1, 392.0, 18), (5.8, 493.9, 19),
             (6.5, 392.0, 20), (7.2, 293.7, 21), (7.9, 196.0, 22)]
    for (t, f, seed) in notes:
        N = int(round(SR / f - 0.5))
        burst = hash_burst(seed, N)
        y = ks_modal(burst, N, rho, int(1.6 * SR))
        place(canvas, y, t)
    write_wav(f"{OUT}/karplus_phrase.wav", canvas)


# ================================================================ engine transcription (banks-as-data)

def ks_mode_rows(burst, N, rho, fmax=20000.0):
    """Collapse the pole/residue table into engine mode rows [f, sigma, amp,
    phase] — each row renders as amp·e^{-sigma·t}·cos(2π·f·t + phase), one real
    damped cosine (the engine's `modalSource` semantics, matching gong.py's
    render_rows). A conjugate pole pair (p, p̄) with residues (A, Ā) collapses
    to 2·Re((A/p)·pⁿ); a lone real pole to a single non-oscillating row. This
    row set is a BIT-EXACT representation of the loop (verified ~260 dB vs the
    recurrence): the whole string is a table of numbers now.

    `fmax` drops modes above a cutoff (default 15 kHz). The top KS partials
    decay in milliseconds (highs die fastest) and sit near Nyquist where the
    engine's integer phasor is least precise — dropping them costs nothing
    audible in the tail, sweetens the attack, and lifts the engine gate SNR."""
    p, A, click = ks_residues(burst, N, rho)
    used = np.zeros(len(p), bool)
    w = np.angle(p)
    rows = []
    for i in range(len(p)):
        if used[i]:
            continue
        sigma = -SR * np.log(np.abs(p[i]))
        if abs(w[i]) < 1e-9:                         # real pole: no pair, no ×2
            used[i] = True
            ac = (A[i] / p[i]).real
            rows.append([0.0, sigma, abs(ac), 0.0 if ac >= 0 else np.pi])
            continue
        j = int(np.argmin(np.abs(p - np.conj(p[i])) + used * 1e9))
        used[i] = used[j] = True
        pos = i if w[i] > 0 else j                   # the +frequency member
        f = abs(w[pos]) * SR / (2 * np.pi)
        if f > fmax:
            continue
        amp_c = A[pos] / p[pos]
        rows.append([f, sigma, 2 * abs(amp_c), float(np.angle(amp_c))])
    return rows, click


def _string_node(nid, rows, t=0.0):
    return {"id": nid, "kind": "string",
            "params": {"t": t, "modes": [[round(x, 9) for x in r] for r in rows]}}


def export_graph():
    """Write the engine graphs (poles as DATA) + numpy recurrence oracles.

      karplus_pluck_graph.json  — one string, seed 17, the tight SNR gate
      karplus_pluck_ref.wav     — its ks_recurrence oracle
      karplus_score_graph.json  — the seed-addressed phrase as string nodes
      karplus_engine_ref.wav    — the phrase's recurrence oracle (the ear)

    The engine renders the SAME table the recurrence oracle validates, so the
    gate (`diffcli render-graph` vs the .wav) prosecutes stateful realization
    against closed-form realization of one object — the gong-pattern move."""
    import json
    # --- single-pluck gate ---
    N, rho, seed, dur = 224, 0.997, 17, 2.0
    burst = hash_burst(seed, N)
    rows, _ = ks_mode_rows(burst, N, rho)
    graph = {"nodes": [_string_node("s0", rows),
                       {"id": "master", "kind": "out", "in": {"in": ["s0"]}}],
             "out": "master"}
    with open(f"{OUT}/karplus_pluck_graph.json", "w") as fh:
        json.dump(graph, fh)
    write_wav(f"{OUT}/karplus_pluck_ref.wav",
              ks_recurrence(burst, N, rho, int(dur * SR)))
    print(f"  wrote karplus_pluck_graph.json ({len(rows)} mode rows) + ref")

    # --- the phrase ---
    notes = [(0.2, 196.0, 11), (0.9, 246.9, 12), (1.6, 293.7, 13),
             (2.3, 392.0, 14), (3.0, 293.7, 15), (3.7, 246.9, 16),
             (4.4, 329.6, 17), (5.1, 392.0, 18), (5.8, 493.9, 19),
             (6.5, 392.0, 20), (7.2, 293.7, 21), (7.9, 196.0, 22)]
    DUR = 9.0
    nodes, mix_ins = [], []
    ref = np.zeros(int(DUR * SR))
    for i, (t, f, sd) in enumerate(notes):
        Nn = int(round(SR / f - 0.5))
        b = hash_burst(sd, Nn)
        rws, _ = ks_mode_rows(b, Nn, rho)
        nodes.append(_string_node(f"s{i}", rws, t=t))
        mix_ins.append(f"s{i}")
        place(ref, ks_recurrence(b, Nn, rho, int(min(1.6, DUR - t) * SR)), t)
    nodes.append({"id": "mixer", "kind": "mix", "in": {"in": mix_ins}})
    nodes.append({"id": "master", "kind": "out", "in": {"in": ["mixer"]}})
    with open(f"{OUT}/karplus_score_graph.json", "w") as fh:
        json.dump({"nodes": nodes, "out": "master"}, fh)
    write_wav(f"{OUT}/karplus_engine_ref.wav", ref)
    print(f"  wrote karplus_score_graph.json ({len(notes)} strings) + ref")


def main():
    snr = prove()
    print()
    render_reversible()
    render_pick_sweep()
    render_stiffness_sweep()
    render_phrase()


if __name__ == "__main__":
    import sys
    if "export" in sys.argv:
        export_graph()
    else:
        main()
