name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ts-typecheck:
    name: TypeScript type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Type-check
        run: bun run tsc --noEmit
