/**
 * bundle_stdlib.ts — generates compiler/stdlib_bundled.ts from stdlib/*.trop.
 *
 * The browser build can't read from disk, so we inline every stdlib program
 * as a TS object literal at build time. Each .trop file is parsed and lowered
 * into the legacy v2 file shape (the same shape loadStdlibFromMap consumes
 * in the disk-reading loader). Re-run whenever stdlib/*.trop changes:
 *
 *   bun web/bundle_stdlib.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, dirname, resolve } from 'path'
import { fileURLToPath } from 'url'
import { extractMarkdown } from '../compiler/parse/markdown.js'
import { parseProgram } from '../compiler/parse/declarations.js'
import { lowerProgram } from '../compiler/parse/lower.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const stdlibDir = resolve(__dirname, '../stdlib')
const outPath = resolve(__dirname, '../compiler/stdlib_bundled.ts')

const files = readdirSync(stdlibDir)
  .filter((f) => f.endsWith('.trop'))
  .sort()

const entries: Array<[string, unknown]> = []
for (const file of files) {
  const text = readFileSync(join(stdlibDir, file), 'utf-8')
  const ext = extractMarkdown(text)
  if (ext.blocks.length !== 1) {
    throw new Error(`${file}: expected exactly 1 tropical block, got ${ext.blocks.length}`)
  }
  const parsed = parseProgram(ext.blocks[0].source)
  const lowered = lowerProgram(parsed)
  const { op: _op, ...fields } = lowered as unknown as Record<string, unknown>
  void _op
  const v2 = { schema: 'tropical_program_2', ...fields } as { schema: string; name?: unknown }
  if (typeof v2.name !== 'string') throw new Error(`${file}: lowered program missing name`)
  entries.push([v2.name, v2])
}

const header = `/**
 * stdlib_bundled.ts — AUTO-GENERATED by web/bundle_stdlib.ts. Do not edit by hand.
 *
 * Inlines every stdlib/*.trop program (parsed and lowered to the v2 file
 * shape) as a TS object literal. Consumed by loadStdlibFromMap() in browser
 * builds where fs is unavailable.
 *
 * Source files (${files.length}): ${files.join(', ')}
 */

export const STDLIB: Record<string, unknown> = `

const body = JSON.stringify(Object.fromEntries(entries), null, 2)
writeFileSync(outPath, header + body + '\n', 'utf-8')

console.log(`wrote ${outPath} (${entries.length} programs, ${body.length} bytes)`)
