/**
 * bundle_stdlib.ts — generates compiler/stdlib_bundled.ts from stdlib/*.json.
 *
 * The browser build can't read from disk, so we inline every stdlib program
 * as a TS object literal at build time. Re-run whenever stdlib/*.json changes.
 *
 *   bun web/bundle_stdlib.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, dirname, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const stdlibDir = resolve(__dirname, '../stdlib')
const outPath = resolve(__dirname, '../compiler/stdlib_bundled.ts')

const files = readdirSync(stdlibDir)
  .filter((f) => f.endsWith('.json'))
  .sort()

const entries: Array<[string, unknown]> = []
for (const file of files) {
  const raw = JSON.parse(readFileSync(join(stdlibDir, file), 'utf-8')) as { name?: string }
  if (typeof raw.name !== 'string') {
    throw new Error(`${file}: missing 'name' field`)
  }
  entries.push([raw.name, raw])
}

const header = `/**
 * stdlib_bundled.ts — AUTO-GENERATED by web/bundle_stdlib.ts. Do not edit by hand.
 *
 * Inlines every stdlib/*.json program as a raw object, keyed by program name.
 * Consumed by loadStdlibFromMap() in browser builds where fs is unavailable.
 *
 * Source files (${files.length}): ${files.join(', ')}
 */

export const STDLIB: Record<string, unknown> = `

const body = JSON.stringify(Object.fromEntries(entries), null, 2)
writeFileSync(outPath, header + body + '\n', 'utf-8')

console.log(`wrote ${outPath} (${entries.length} programs, ${body.length} bytes)`)
