/**
 * bundle_stdlib.ts — generates compiler/stdlib_bundled.ts from stdlib/*.md.
 *
 * The browser build can't read from disk, so we inline every stdlib program
 * as raw tropical source text (the single ```tropical block extracted from
 * each literate .md document; README.md is skipped by name). The runtime
 * (`loadStdlibFromSources` in `compiler/stdlib_loader.ts`) parses each
 * source, elaborates against a sibling-resolver, and feeds the resolved IR
 * through the strata pipeline.
 *
 *   bun web/bundle_stdlib.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, dirname, resolve } from 'path'
import { fileURLToPath } from 'url'
import { extractMarkdown } from '../compiler/parse/markdown.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const stdlibDir = resolve(__dirname, '../stdlib')
const outPath = resolve(__dirname, '../compiler/stdlib_bundled.ts')

const files = readdirSync(stdlibDir)
  .filter((f) => f.endsWith('.md') && f !== 'README.md')
  .sort()

const entries: Array<[string, string]> = []
for (const file of files) {
  const text = readFileSync(join(stdlibDir, file), 'utf-8')
  const ext = extractMarkdown(text)
  if (ext.blocks.length !== 1) {
    throw new Error(`${file}: expected exactly 1 tropical block, got ${ext.blocks.length}`)
  }
  const name = file.replace(/\.md$/, '')
  entries.push([name, ext.blocks[0].source])
}

const header = `/**
 * stdlib_bundled.ts — AUTO-GENERATED by web/bundle_stdlib.ts. Do not edit by hand.
 *
 * Inlines every stdlib/*.md program's tropical code block as raw source text.
 * Consumed by loadStdlibFromSources() in browser builds where fs is
 * unavailable; the source text is parsed, elaborated, and fed through
 * the strata pipeline at load time.
 *
 * Source files (${files.length}): ${files.join(', ')}
 */

export const STDLIB_SOURCES: Record<string, string> = `

const body = JSON.stringify(Object.fromEntries(entries), null, 2)
writeFileSync(outPath, header + body + '\n', 'utf-8')

console.log(`wrote ${outPath} (${entries.length} programs, ${body.length} bytes)`)
